---
# Main playbook driving the entire configuration

- name: Common configuration
  hosts: all
  roles:
    - role: common
      tags: common

- name: WireGuard configuration
  hosts: wireguard
  roles:
    - role: wireguard
      tags:
        - wireguard
        - network

- name: Apache webserver configuration
  hosts: apache2
  roles:
    - role: apache2
      tags: apache2

- name: approx configuration
  hosts: approx
  roles:
    - role: approx
      tags: approx

- name: reprepro configuration
  hosts: reprepro
  roles:
    - role: reprepro
      tags: reprepro

- name: RabbitMQ configuration
  hosts: rabbitmq
  roles:
    - role: rabbitmq
      tags: rabbitmq

- name: rsnapshot configuration
  hosts: rsnapshot
  roles:
    - role: rsnapshot
      tags: rsnapshot

- name: debci-master configuration
  hosts: debci_master
  roles:
    - role: debci_master
      tags:
        - debci
        - debci_master

- name: debci-worker configuration
  hosts: debci_worker
  roles:
    - role: debci_worker
      tags:
        - debci
        - debci_worker
