---
- name: Apache web server configuration
  import_tasks: apache2.yml
  tags:
    - apache
    - apache2
    - www
    - webserver

- name: Apache web server firewalld configuration
  import_tasks: firewalld.yml
  tags:
    - apache
    - apache2
    - www
    - webserver
    - firewalld

# We do this after firewalld, as this needs port 80 open
- name: Let's Encrypt certficate management
  when: acme_domains | length > 0
  import_tasks: dehydrated.yml
  tags:
    - apache
    - apache2
    - www
    - webserver
    - letsencrypt
    - dehydrated
