---
- name: approx => Package is installed
  apt:
    name: approx
    state: present

- name: approx => /var/cache/approx exists
  file:
    path: /var/cache/approx
    state: directory
    owner: approx
    group: approx
    mode: 0755

- name: approx => Configure /etc/approx.conf
  template:
    src: approx/approx.conf.j2
    dest: /etc/approx/approx.conf
    owner: root
    group: root
    mode: "0755"
