---
- name: Restart firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes

- name: Restart Apache webserver
  service:
    name: apache2
    state: restarted
    enabled: yes

- name: Restart OpenSSH server
  service:
    name: ssh
    state: restarted
    enabled: yes

- name: Restart RabbitMQ server
  service:
    name: rabbitmq-server
    state: restarted
